spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 410274513083-0vkgor9pdb5d8feb98rq0mb11khgbq6a.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            authorization-grant-type: authorization_code
            client-authentication-method: post
            provider: google
          github:
            client-id: Ov23liXCoqwDK6Kagt25
            client-secret: 315bda9b44719e76673f54150d4c7582220128cb
            scope: user
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-authentication-method: post
            provider: github
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user